### ISSUE TITLE
Celery bug for Keras model predictions

### ISSUE THREAD

**Issue by YohanMedalsy** [eliorc/denzel#4]
Hi,

I have been struggling a lot to use this library for my Keras model deployment. After a lot of hard work understanding the entire structure of the library and pinpointing the problem, I would like to address it here for improvements in future releases.

https://stackoverflow.com/questions/45459205/keras-predict-not-returning-inside-celery-task

**Comment by eliorc** [comment]
Me and @YohanMedalsy have been discussing this issue in private and its a result of keras not being thread safe and celery (which is used in this library) using threads to execute concurrently. 

I did not have the spare time to put into this - but once I will, I'll attend this 

Thanks @YohanMedalsy
